#ifndef EZS_PP_STRINGIFY_ARG_LIST_HPP_
#define EZS_PP_STRINGIFY_ARG_LIST_HPP_
#define STRINGIFY_ARG_LIST_0(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_1(__VA_ARGS__))
#define STRINGIFY_ARG_LIST_1(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_2(__VA_ARGS__))
#define STRINGIFY_ARG_LIST_2(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_3(__VA_ARGS__))
#define STRINGIFY_ARG_LIST_3(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_4(__VA_ARGS__))
#define STRINGIFY_ARG_LIST_4(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_5(__VA_ARGS__))
#define STRINGIFY_ARG_LIST_5(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_6(__VA_ARGS__))
#define STRINGIFY_ARG_LIST_6(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_7(__VA_ARGS__))
#define STRINGIFY_ARG_LIST_7(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_8(__VA_ARGS__))
#define STRINGIFY_ARG_LIST_8(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_9(__VA_ARGS__))
#define STRINGIFY_ARG_LIST_9(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_10(__VA_ARGS__))
#define STRINGIFY_ARG_LIST(HEAD, ...) #HEAD __VA_OPT__(, STRINGIFY_ARG_LIST_0(__VA_ARGS__))
#endif
