SRC_ADT_PTR_DIR := $(GET_CURRENT_DIR)

MODULES += ezs.adt.Ptr ezs.adt.Ptr.fwd ezs.adt.Ptr_test

ezs.adt.Ptr_INTERFACE_FILE := $(SRC_ADT_PTR_DIR)/Ptr.hxx
ezs.adt.Ptr_INTERFACE_DEPS := ezs.adt.Value

ezs.adt.Ptr.fwd_INTERFACE_FILE := $(SRC_ADT_PTR_DIR)/Ptr.fwd.hxx
ezs.adt.Ptr.fwd_INTERFACE_DEPS := ezs.adt.Value

ezs.adt.Ptr_test_IMPLEMENTATION_FILE := $(SRC_ADT_PTR_DIR)/Ptr.test.cpp
ezs.adt.Ptr_test_IMPLEMENTATION_DEPS := ezs.adt.Ptr ezs.test.Test
