SRC_MAIN_DIR := $(GET_CURRENT_DIR)

MODULES += ezs.main.Main ezs.main.Test
MAIN_MODULES += ezs.main.Main ezs.main.Test

ezs.main.Main_IMPLEMENTATION_FILE := $(SRC_MAIN_DIR)/Main.cpp
ezs.main.Main_IMPLEMENTATION_DEPS := ezs ezs.adt.Value ezs.adt.Ptr

ezs.main.Test_IMPLEMENTATION_FILE := $(SRC_MAIN_DIR)/Test.cpp
ezs.main.Test_IMPLEMENTATION_DEPS := ezs.test.Test ezs_test
