SRC_ADT_DIR := $(GET_CURRENT_DIR)

MODULES += ezs.adt

ezs.adt_INTERFACE_FILE := $(SRC_ADT_DIR)/adt.hxx
ezs.adt_INTERFACE_DEPS := ezs.adt.Ptr ezs.adt.Value

include $(SRC_ADT_DIR)/Ptr/Makefile
include $(SRC_ADT_DIR)/Value/Makefile
