SRC_PP_DIR := $(GET_CURRENT_DIR)

MODULES += test.ezs.pp

test.ezs.pp_IMPLEMENTATION_DEPS := test.ezs.pp.EXPAND_STRINGIFY

include $(SRC_PP_DIR)/STRINGIFY/STRINGIFY.mk
include $(SRC_PP_DIR)/CONCAT/CONCAT.mk
include $(SRC_PP_DIR)/APPLY/APPLY.mk
include $(SRC_PP_DIR)/EXPAND_STRINGIFY/EXPAND_STRINGIFY.mk
include $(SRC_PP_DIR)/EXPAND_CONCAT/EXPAND_CONCAT.mk
include $(SRC_PP_DIR)/UNIQUE/UNIQUE.mk
